plugins { id 'com.android.application' }

android {
    namespace 'top.aiygzn.melodica'
    compileSdk 34
    defaultConfig {
        applicationId 'top.aiygzn.melodica'
        minSdk 26
        targetSdk 34
        versionCode 5
        versionName '0.5.0-preview'
        testInstrumentationRunner project.findProperty('testRunner') ?: 'top.aiygzn.melodica.GestureSmokeTest'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}

tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
